version: "3.3"

services:

  web:
    build:
      context: "."
      dockerfile: Dockerfile
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
    ports:
      - 80:80
  init:
    build:
      context: "."
      dockerfile: .dockerfile
    depends_on: 
      - web
    restart: "no"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
